name: ${project.name}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
author: ${project.author}
commands:
  enchants:
    usage: /<command>
    description: Open the custom enchants gui
    aliases: [ce, enchanter, enchant]